### ISSUE TITLE
ellipse bounding box

### ISSUE THREAD

**Issue by cantika98** [salemchen/siammask_e#10]
how do you create the ellipse bounding box?

**Comment by baoxinchen** [comment]
Hi amandakam,
Thanks for your question. To convert the ellipse to a rectangular bounding box, please refer to my workshop paper [SiamMask_E](https://arxiv.org/abs/1907.03892) Figure 3 for more details.
And, the code is in this file pysot/tracker/siammask_e_tracker.py

**Comment by cantika98** [comment]
thank you for your answer
