### ISSUE TITLE
请问把代码放到Pysot中，可以训练吗

### ISSUE THREAD

**Issue by EEEEEREN** [salemchen/siammask_e#13]
请问把代码按照要求放到pysot中，可以训练吗
pysot中的siammask感觉配置文件不全，我弄了好久都没有训练出来
请问这个放进去，可以在pysot中训练siammask_e吗

**Comment by baoxinchen** [comment]
您好！模型训练的问题请咨询SiamMask原作者

**Comment by EEEEEREN** [comment]
就是请问，我怎么样才可以训练您的代码呢，我把您的代码放到pysot中，但是不成功

**Comment by baoxinchen** [comment]
我这些代码不是训练模型用的，只是增强SiamMask的原生模型。只要你有一个比较好的Mask tracking算法都可以用ellipse fitting来增强UoI。

**Comment by EEEEEREN** [comment]
噢噢噢噢 我懂了，感谢感谢
