### ISSUE TITLE
Which one is SiamMask E ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [salemchen/siammask_e#4]
This is the models i found in [PySOT ZOO](https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md) which one is the SiamMask E ?

![Screenshot from 2019-11-20 21-22-12](https://user-images.githubusercontent.com/26205298/69270586-e2db7d00-0bdb-11ea-8769-75c09457275d.png)

**Comment by baoxinchen** [comment]
Hi,
Please download siammask_r50_l3 model, and place it in "experiments/siammaske_r50_l3" folder.
Don't change config.yaml in this folder.
