### ISSUE TITLE
Question about SiamMask EAO

### ISSUE THREAD

**Issue by vexilligera** [salemchen/siammask_e#5]
Hi, thanks for the great work. In the SiamMask paper, the EAO they reported on VOT 2018 is 0.380, which is lower than the number in your experiment (0.406). I am having trouble reproducing the SiamMask result (using the code in their repo I only got ~0.29 in the base model), and I'm wondering if you could share some details in SiamMask training? Thanks.

**Comment by baoxinchen** [comment]
Hi,
0.406 was reported using the same model from SiamMask. In this work, I didn't train any new model. You might email the SiamMask original authors.
