### ISSUE TITLE
Hello! The result achieved by your project is excellent. I would like to ask if I want to replace the siammask_e model with another trained model. Where could I change it?

### ISSUE THREAD

**Issue by HaoyuanXu** [salemchen/siammask_e#6]
您好！您的项目实现的效果很出色 我想请教一下 如果我想用另一个训练好的模型替换siammask_e模型 该从哪里改呢

**Comment by baoxinchen** [comment]
Hi Haoyuan Xu,
Thanks for your question!
To train a new model, please refer to the original [SiamMask](https://github.com/foolwood/SiamMask). The author has the training code in "tools" folder.

**Comment by HaoyuanXu** [comment]
Thank you for your reply！Can I just run pysot's "train.py" in its "tools"folder instead of SiamMask's?

**Comment by baoxinchen** [comment]
Hi Haoyuan Xu,
pysot does not have the training code for SiamMask. Please train the model using the training code in [SiamMask](https://github.com/foolwood/SiamMask). You also need to follow "readme.md" file to download and prepare training data.
