### ISSUE TITLE
So I need to train siammask_e in pysot folder,but using /tools/train_siammask.py in SiamMask?

### ISSUE THREAD

**Issue by HaoyuanXu** [salemchen/siammask_e#9]
Thank u in advance

**Comment by baoxinchen** [comment]
Hi Xu,
SiamMask_E uses the same mode as SiamMask. You need to train a SiamMask model in [SimaMask](https://github.com/foolwood/SiamMask), then copy the model file to [PySot](https://github.com/STVIR/pysot).
